const STOCK_DATA = [
  {
    id: 1,
    symbol: "aapl",
    details: {
      actual_return: 4.66,
      buy_value: 61.77,
      currency: "USD",
      current_price: 337.33,
      dividen_rate: 3.28,
      eps: 12.728,
      exchange: "NMS",
      growth: 3.69,
      industry: "Consumer Electronics",
      longName: "Apple Inc.",
      roe: 0.62094,
      sector: "Technology",
    },
  },
  {
    id: 2,
    symbol: "fbk.mi",
    details: {
      actual_return: 6.47,
      buy_value: 0.0,
      currency: "EUR",
      current_price: 11.72,
      dividen_rate: 0,
      eps: 0.522,
      exchange: "MIL",
      growth: 6.47,
      industry: "Banks—Regional",
      longName: "FinecoBank Banca Fineco S.p.A.",
      roe: 0.2523,
      sector: "Financial Services",
    },
  },
  {
    id: 3,
    symbol: "g.mi",
    details: {
      actual_return: 9.82,
      buy_value: 17.17,
      currency: "EUR",
      current_price: 13.39,
      dividen_rate: 0.5,
      eps: 1.678,
      exchange: "MIL",
      growth: 6.09,
      industry: "Insurance—Diversified",
      longName: "Assicurazioni Generali S.p.A.",
      roe: 0.09043,
      sector: "Financial Services",
    },
  },
  {
    id: 4,
    symbol: "mmm",
    details: {
      actual_return: 9.53,
      buy_value: 180.18,
      currency: "USD",
      current_price: 155.1777,
      dividen_rate: 5.88,
      eps: 8.523,
      exchange: "NYQ",
      growth: 5.74,
      industry: "Specialty Industrial Machinery",
      longName: "3M Company",
      roe: 0.49915,
      sector: "Industrials",
    },
  },
  {
    id: 5,
    symbol: "pg",
    details: {
      actual_return: 3.63,
      buy_value: 28.45,
      currency: "USD",
      current_price: 115.64,
      dividen_rate: 3.16,
      eps: 1.856,
      exchange: "NYQ",
      growth: 0.89,
      industry: "Household & Personal Products",
      longName: "The Procter & Gamble Company",
      roe: 0.100109994,
      sector: "Consumer Defensive",
    },
  },
];

export default STOCK_DATA;
